server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backenddb
    username: Mike
    password: inapfVTmm09^^UWU
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop #when in production change to "update"
      transaction:
        jta:
          platform: org.hibernate.service.jta.platform.internal.JBossStandAloneJtaPlatform
    show-sql: true

  application:
    name: USER-SERVICE
