security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    url: jdbc:mysql://localhost:5432/backenddb #change this
    username: root #change this
    password: root #change this
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop #create? update?
    show-sql: true

  application:
    name: USER-SERVICE
